### ISSUE TITLE
Add pub cache bin dir to PATH

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/dart_docker#10]
Any app that wants to run [pub global activate](https://www.dartlang.org/tools/pub/cmd/pub-global.html#running-a-script-from-your-path)d executables will have to add this to their dockerfile:

`ENV PATH $PATH:~/.pub-cache/bin`

It would be nice if `google/dart` could do this for us.

**Comment by cedx** [comment]
You can still use: `pub global run <executable>`
https://dart.dev/tools/pub/cmd/pub-global#running-a-script-using-pub-global-run

**Comment by athomas** [comment]
Should've been fixed by 331a72627a4927430aa167a40b5a89efad00bda1.
