### ISSUE TITLE
Tag images dev and stable

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/dart_docker#11]
It would be nice to have multiple tags for tracking dev and stable for CI systems.

http://stackoverflow.com/questions/21928780/create-multiple-tag-docker-image

Has an example on how to tag the same image multiple times.

Might also be nice to have a google/dart:1.12 similar to what nodejs does for images.

**Comment by sgjesse** [comment]
@mit-mit @whesse 

So your suggestion is to have the tag 'latest' or 'stable' move together with a new stable release, have the '1.12' tag move with a new 1.12 release and have the 'dev' tag move with a new developer release.

That sounds like a good idea.

**Comment by donny-dont** [comment]
Yep that would be what I'd think you'd want to do though stable should probably just be latest to fit with the convention. Also in terms of dev you could have a dev tag and also a 1.13 tag. Once the dev is gone that would follow the stable.

**Comment by donny-dont** [comment]
@sgjesse I think I have this sorted out in #12 if you can take a look to make sure it builds properly on Google's infrastructure.
