### ISSUE TITLE
Running pub get before adding project dir in dart-runtime prevents path dependencies

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/dart_docker#15]
Consider you ship your app with a private library as a dependency. You don't want to publish that to pub.

What I do is add a git submodule to `./modules/private-library` and add a dependency:

```
dependencies:
  priv_lib:
    path: modules/private-library
```

However the dar t-runtime Docker first only adds the pubspec file and then runs pub get before adding the rest of the project directory. This prevents the pub get from finding the private library.

Why is it done in this order?

**Comment by sgjesse** [comment]
The `dart-runtime` base image is intended for the simple case where you just pull packages from pub. In your situation with local packages as well you can use the `dart-runtime-base` base image. It requires a bit more configuration in terms of the Dockerfile to provide, but gives the flexibility to use local packages. Take a look at the [documentation](https://github.com/dart-lang/dart_docker/tree/master/runtime-base), to see if that fits your needs.
