### ISSUE TITLE
Become official Docker library

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/dart_docker#18]
Currently Dart is under the google namespace. It would be great if this was an official Docker library so you could pull `dart` instead of `google/dart`.

**Comment by kevmoo** [comment]
See

https://github.com/docker-library/official-images/pull/10144
and
https://github.com/docker-library/docs/pull/1944

**Comment by athomas** [comment]
We'll deprecate this repo once dart-lang/dart-docker (with a `-` rather than a `_` goes official). We'll still publish to google/dart for a while in parallel but we won't be evolving the containers in this repo anymore.

**Comment by subfuzion** [comment]
For the repo for our candidate official image, see:
https://github.com/dart-lang/dart-docker

**Comment by kevmoo** [comment]
Fixed in https://github.com/docker-library/official-images/commit/5f961ff5ebed1de08908203d55382f3a60fe49c7

**Comment by subfuzion** [comment]
And you can now use `FROM dart`, folks! 🚀
https://hub.docker.com/_/dart
