### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by ronlobo** [dart-lang/dart_docker#20]
Hey there,

As boot2docker is deprecated and gcloud container is not longer in preview you might want to update the setup steps for the examples.

Thx

**Comment by oonid** [comment]
Hello,

I have an additional request, would be great to have the examples updated with Google Cloud Run.

thank you.

**Comment by mit-mit** [comment]
Closing: this has been replaced by a new image, which has up-to-date instructions: https://hub.docker.com/_/dart
