### ISSUE TITLE
Dart now requires debian/jessie base image

### ISSUE THREAD

**Issue by whesse** [dart-lang/dart_docker#23]
The linux debian package is now compiled on wheezy, and requires libc 2.16, while jessie has 2.14.
This was required because we need a C++11 compiler to build dart.

Let me know if you think this will be a problem.  The CL to do this is at
https://codereview.chromium.org/2264393003/

@donny-dont @evils @kevmoo @sgjesse

**Comment by donny-dont** [comment]
LGTM

**Comment by evils** [comment]
👍

**Comment by kevmoo** [comment]
Fixed with https://github.com/dart-lang/dart_docker/commit/922e0457a9b4ca80ce707582cee32c2ee3250f24
