### ISSUE TITLE
define ENV PORT 8080 for dart-runtime(-base)

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/dart_docker#31]
If the image expects applications to on port `8080` it would be nice to define the environment variable `PORT`.

Because:

1. It does no harm.
2. It's common for applications to listen on `PORT` (at-least for lots of developers targeting heroku).
3. Hmm, I guess I think it's a useful contract for applications to have, making them slightly more portable.
4. Okay, I'm possibly missing good arguments, maybe it just _feels_ idiomatic for the space..

We can do this by adding:
```Dockerfile
ENV PORT 8080
```

**Comment by kevmoo** [comment]
Fixed in https://github.com/athomas/dart_docker/commit/b104807fdd67e7a1af910d8e0eff44e10a4b6f00 @jonasfj @domesticmouse ?

**Comment by kevmoo** [comment]
Can close?

**Comment by domesticmouse** [comment]
Do we close issues when they are checked into head, or when we push out a release that contains the fix?

**Comment by kevmoo** [comment]
Usually when checked into HEAD.
