### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by enyo** [dart-lang/dart_docker#47]
I've upgraded the dart Docker image to `2.3.1` (and have also tested the dev version `2.3.2` and in both instances, when I run my CI tests I can't write any files anymore. I always get:

`Failed to set file modification time, path = './pubspec.lock' (OS Error: Operation not permitted, errno = 1)`

I've downgraded to Docker `2.2.0` and rebuilt the image the same way, and it worked again, so it is definitely related to the `2.3.x` images. Any idea how I could solve this?

**Comment by jonasfj** [comment]
Minimal steps to reproduce?

I can do `pub get` in `google/dart:2.3.1`

**Comment by enyo** [comment]
I'll get them to you tomorrow. Thanks for checking it out.

**Comment by enyo** [comment]
Sorry. It is related to a change in dart 2.3.1 that tries to write pubspec.lock which was never writable in our case.

Thanks for your help.
