### ISSUE TITLE
Update the "git" executable

### ISSUE THREAD

**Issue by cedx** [dart-lang/dart_docker#52]
The Docker image uses Git v2.11.0, but this version is not compatible with GitHub Actions which require Git v2.18.0 or later.

In the job logs, we can see this message:

```
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
```

This breaks the code coverage of my Dart projects, which collect various Git data before sending the coverage report to [Coveralls](https://coveralls.io).

**Comment by jonasfj** [comment]
Probably we have to update base image to debian 10.

There we'll have:
```
root@34b563139827:/# git --version
git version 2.20.1
```
