### ISSUE TITLE
Update "latest" image

### ISSUE THREAD

**Issue by JSANL** [dart-lang/dart_docker#54]
Latest stable version is (at the moment of writing) Dart 2.7.1, the "lastest" image version on docker hub is 2.6.1. Like the new versions are on docker hub, just the "latest" version is well... not the latest (stable).

**Comment by jonasfj** [comment]
https://hub.docker.com/layers/google/dart/2.7.1/images/sha256-90ab0107f184070f430ceb6e297731d6fa29eec6177892494d834ed77ce3d29a

has same hash as

https://hub.docker.com/layers/google/dart/latest/images/sha256-90ab0107f184070f430ceb6e297731d6fa29eec6177892494d834ed77ce3d29a

so I think this just your local docker cache.. try `docker pull google/dart:latest` or `docker pull google/dart`.
