### ISSUE TITLE
Add an AOT serving image

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart_docker#66]
See https://github.com/subfuzion/dart-docker-slim

Would be great to make this "official"

CC @athomas @mit-mit @subfuzion

**Comment by mit-mit** [comment]
What us a "compiling image"?

**Comment by kevmoo** [comment]
https://github.com/subfuzion/dart-docker-slim

An image that does the AOT compiling work.

Would be great if this was part of our official offering.

CC @subfuzion

**Comment by mit-mit** [comment]
I'm not sure we need a compiling image (for that you need the full SDK, this is the "fat image"). What we need is a slim "serving image" that has just enough to run an AOT-compiled snapshot in the VM.

**Comment by kevmoo** [comment]
> I'm not sure we need a compiling image (for that you need the full SDK, this is the "fat image"). What we need is a slim "serving image" that has just enough to run an AOT-compiled snapshot in the VM.

renamed the issue

**Comment by subfuzion** [comment]
To help eliminate any confusion when referring to the images, let's call them the `sdk` and `runtime` images. Using `runtime` was recommended by the official images team (Tianon), vs `slim` and other choices.

**Comment by subfuzion** [comment]
I'm been brainstorming with Tianon over slack for the past couple of hours. We're thinking we might be able to optimize things in such a way that we can generate the final version of an image in one of two ways, both of which would eliminate the need to actually maintain a dedicated runtime image. Will circle back here with more details shortly.

**Comment by mit-mit** [comment]
> let's call them the sdk and runtime images

SGTM

**Comment by mit-mit** [comment]
Re brainstorming, not sure if this makes any difference, but note that there is an alternative to compiling to a `server.exe` as the current slim image does, namely to compile to an [AOT snapshot](https://dart.dev/tools/dart-compile#aot-snapshot) and then run this with the small [`dartaotruntime`](https://dart.dev/tools/dartaotruntime), where the latter is a fixed runtime that doesn't depend on the app being run.

**Comment by mit-mit** [comment]
Closing: we now have this supported in https://hub.docker.com/_/dart
