### ISSUE TITLE
Have a `dart-runtime`-like option without Observatory

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart_docker#69]
Comparing `ProcessInfo.maxRss` between the current `dart-runtime`
With observatory: 253,034,496

And the `Dockerfile` below.

Without: 208,384,000

This ends up mattering quite a bit because the default memory of a Cloud Run instance is 256MB. It seems I hit a memory ceiling about 25% of the time when I deploy a service. Dropping the ~45MB of RAM gives us the headroom where we hopefully won't hit it for most folks!

```docker
# Use Google's official Dart image.
# https://hub.docker.com/r/google/dart-runtime/
FROM google/dart

ENV PORT 8080

WORKDIR /app

ADD pubspec.* /app/
RUN pub get
ADD . /app/
RUN pub get --offline

CMD ["dart", "/app/bin/server.dart"]
```

**Comment by mit-mit** [comment]
Maybe we do a `dart-runtime-slim` which doesn't have observatory, and uses AOT-compilation?

**Comment by kevmoo** [comment]
Are there reasons to keep those options separate?

maybe not...

**Comment by mit-mit** [comment]
I think it actually makes sense to bundle those two as the AOT runtime doesn't have observatory, right?

**Comment by athomas** [comment]
I'm closing this, I think the official images cover that use case in the documentation.
